#!/bin/sh

FONT_FILES="SLPSansBold_1119.ttf SLPSansMedium_1119.ttf SLPSansRegular_1119.ttf SLPSansLight_1119.ttf SLPSansFallbackBold.ttf SLPSansFallbackMedium.ttf SLPSansFallbackRegular.ttf VeraSe.ttf VeraSeBd.ttf"

if [ ${USER} == "root" ]
then
	# Change file owner
	# Font files
	for file in `echo $FONT_FILES`
	do
		chown root:root /usr/share/fonts/$file
	done
fi

# Font files
for file in `echo $FONT_FILES`
do
	chmod 644 /usr/share/fonts/$file
done
	
